apiVersion: apps/v1
kind: Deployment
metadata:
  name: obligatorio-be-products-devops
  labels:
    app: products-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-app
          image: 206798921196.dkr.ecr.us-east-1.amazonaws.com/ecr_demo_obli:products_devops
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
