apiVersion: apps/v1
kind: Deployment
metadata:
  name: obligatorio-be-payments-devops
  labels:
    app: payments-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-app
  template:
    metadata:
      labels:
        app: payments-app
    spec:
      containers:
        - name: payments-app
          image: 206798921196.dkr.ecr.us-east-1.amazonaws.com/ecr_demo_obli:payments_devops
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
